### ISSUE TITLE
cookies 

### ISSUE THREAD

**Issue by tanmaygaikwad723** [ismaelfi/Scrape-Linkedin-Posts#1]
Cant figure out which cookies/how the cookies needed to be stored

**Comment by ismaelfi** [comment]
Use the extension : Get cookies.txt LOCALLY
https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc?hl=fr&utm_source=ext_sidebar

Then Go to Linkedin.com , open the extension and click export 

it should download a TXT file 

![Capture d’écran 2024-08-12 à 12 16 04](https://github.com/user-attachments/assets/1f2d3a34-9347-44e7-ac4b-dc0497152244)
