### ISSUE TITLE
Post quantity without LinkedIn restrictions

### ISSUE THREAD

**Issue by pmcintyr** [ismaelfi/Scrape-Linkedin-Posts#2]
Hi there,

Have you found the specific limitations of scraped post quantity before accounts get restricted?

I get restrictions after around 4-5x50 scraped posts and want to avoid getting hit again.

Cheers,
Paul

**Comment by ismaelfi** [comment]
Hi Paul, 
To avoid restrictions, you should add time between requests, using random intervals. or rotating IPs
